"""Add delivery module tables

Revision ID: 9b0bf3bd360d
Revises: 7af7c8bad3d6
Create Date: 2026-07-06 02:07:57.032449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9b0bf3bd360d'
down_revision: Union[str, Sequence[str], None] = '7af7c8bad3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_tabs_id'), table_name='tabs')
    op.drop_table('tabs')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_biometric_consents_id'), table_name='biometric_consents')
    op.drop_table('biometric_consents')
    op.drop_index(op.f('ix_biometric_events_created_at'), table_name='biometric_events')
    op.drop_index(op.f('ix_biometric_events_id'), table_name='biometric_events')
    op.drop_index(op.f('ix_biometric_events_profile_id'), table_name='biometric_events')
    op.drop_table('biometric_events')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_key'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_stock_item_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_internal_consumptions_id'), table_name='internal_consumptions')
    op.drop_table('internal_consumptions')
    op.drop_index(op.f('ix_loss_records_id'), table_name='loss_records')
    op.drop_index(op.f('ix_loss_records_stock_item_id'), table_name='loss_records')
    op.drop_table('loss_records')
    op.drop_index(op.f('ix_stock_items_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_name'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_discount_logs_id'), table_name='discount_logs')
    op.drop_index(op.f('ix_discount_logs_order_id'), table_name='discount_logs')
    op.drop_table('discount_logs')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_cash_registers_date'), table_name='cash_registers')
    op.drop_index(op.f('ix_cash_registers_id'), table_name='cash_registers')
    op.drop_table('cash_registers')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_kitchen_orders_id'), table_name='kitchen_orders')
    op.drop_index(op.f('ix_kitchen_orders_order_id'), table_name='kitchen_orders')
    op.drop_table('kitchen_orders')
    op.drop_index(op.f('ix_seasonality_metrics_id'), table_name='seasonality_metrics')
    op.drop_index(op.f('ix_seasonality_metrics_metric_type'), table_name='seasonality_metrics')
    op.drop_table('seasonality_metrics')
    op.drop_index(op.f('ix_monthly_account_items_id'), table_name='monthly_account_items')
    op.drop_table('monthly_account_items')
    op.drop_index(op.f('ix_signatures_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_cash_movements_cash_register_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_created_at'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_restaurant_settings_id'), table_name='restaurant_settings')
    op.drop_table('restaurant_settings')
    op.drop_index(op.f('ix_orders_client_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_delivery_addresses_client_id'), table_name='delivery_addresses')
    op.drop_index(op.f('ix_delivery_addresses_id'), table_name='delivery_addresses')
    op.drop_table('delivery_addresses')
    op.drop_index(op.f('ix_biometric_profiles_client_id'), table_name='biometric_profiles')
    op.drop_index(op.f('ix_biometric_profiles_id'), table_name='biometric_profiles')
    op.drop_table('biometric_profiles')
    op.drop_index(op.f('ix_restaurant_tables_id'), table_name='restaurant_tables')
    op.drop_table('restaurant_tables')
    op.drop_index(op.f('ix_insight_logs_id'), table_name='insight_logs')
    op.drop_index(op.f('ix_insight_logs_insight_type'), table_name='insight_logs')
    op.drop_table('insight_logs')
    op.drop_index(op.f('ix_monthly_accounts_client_id'), table_name='monthly_accounts')
    op.drop_index(op.f('ix_monthly_accounts_id'), table_name='monthly_accounts')
    op.drop_table('monthly_accounts')
    op.drop_index(op.f('ix_tab_items_id'), table_name='tab_items')
    op.drop_table('tab_items')
    op.drop_index(op.f('ix_delivery_events_id'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_order_id'), table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_index(op.f('ix_product_recipes_id'), table_name='product_recipes')
    op.drop_index(op.f('ix_product_recipes_product_id'), table_name='product_recipes')
    op.drop_table('product_recipes')
    op.drop_index(op.f('ix_kitchen_order_events_id'), table_name='kitchen_order_events')
    op.drop_table('kitchen_order_events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_combo_items_id'), table_name='combo_items')
    op.drop_table('combo_items')
    op.drop_index(op.f('ix_product_recipe_items_id'), table_name='product_recipe_items')
    op.drop_table('product_recipe_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_recipe_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_item_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_required', sa.FLOAT(), nullable=False),
    sa.Column('unit_measure', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['product_recipes.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_recipe_items_id'), 'product_recipe_items', ['id'], unique=False)
    op.create_table('combo_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('combo_product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['combo_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_items_id'), 'combo_items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('kitchen_order_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kitchen_order_id', sa.INTEGER(), nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('performed_by', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['kitchen_order_id'], ['kitchen_orders.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_order_events_id'), 'kitchen_order_events', ['id'], unique=False)
    op.create_table('product_recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('estimated_margin', sa.FLOAT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_recipes_product_id'), 'product_recipes', ['product_id'], unique=1)
    op.create_index(op.f('ix_product_recipes_id'), 'product_recipes', ['id'], unique=False)
    op.create_table('delivery_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_events_order_id'), 'delivery_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_delivery_events_id'), 'delivery_events', ['id'], unique=False)
    op.create_table('tab_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tab_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tab_items_id'), 'tab_items', ['id'], unique=False)
    op.create_table('monthly_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_by', sa.INTEGER(), nullable=True),
    sa.Column('biometric_verification_id', sa.INTEGER(), nullable=True),
    sa.Column('biometric_verified_at', sa.DATETIME(), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('paid_by', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_accounts_id'), 'monthly_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_accounts_client_id'), 'monthly_accounts', ['client_id'], unique=False)
    op.create_table('insight_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('insight_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_logs_insight_type'), 'insight_logs', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insight_logs_id'), 'insight_logs', ['id'], unique=False)
    op.create_table('restaurant_tables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_restaurant_tables_id'), 'restaurant_tables', ['id'], unique=False)
    op.create_table('biometric_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('encrypted_template', sa.TEXT(), nullable=False),
    sa.Column('algorithm', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fingers_enrolled', sa.INTEGER(), nullable=True),
    sa.Column('device_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_profiles_id'), 'biometric_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_biometric_profiles_client_id'), 'biometric_profiles', ['client_id'], unique=1)
    op.create_table('delivery_addresses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('street', sa.VARCHAR(length=200), nullable=False),
    sa.Column('number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reference', sa.TEXT(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_addresses_id'), 'delivery_addresses', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_addresses_client_id'), 'delivery_addresses', ['client_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tab_id', sa.INTEGER(), nullable=True),
    sa.Column('table_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('delivery_address_id', sa.INTEGER(), nullable=True),
    sa.Column('delivery_fee', sa.FLOAT(), nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('delivery_person_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('estimated_delivery_time', sa.DATETIME(), nullable=True),
    sa.Column('delivered_at', sa.DATETIME(), nullable=True),
    sa.Column('preparation_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['delivery_addresses.id'], ),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_client_id'), 'orders', ['client_id'], unique=False)
    op.create_table('restaurant_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('opening_hours', sa.VARCHAR(length=255), nullable=True),
    sa.Column('service_fee_percent', sa.FLOAT(), nullable=True),
    sa.Column('delivery_fee_default', sa.FLOAT(), nullable=True),
    sa.Column('default_monthly_limit', sa.FLOAT(), nullable=True),
    sa.Column('default_due_days', sa.INTEGER(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cancellation_policy', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_settings_id'), 'restaurant_settings', ['id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cash_register_id', sa.INTEGER(), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('performed_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_id'), 'cash_movements', ['id'], unique=False)
    op.create_index(op.f('ix_cash_movements_created_at'), 'cash_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_cash_movements_cash_register_id'), 'cash_movements', ['cash_register_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monthly_account_id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('paid_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['monthly_account_id'], ['monthly_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('signatures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monthly_account_id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('signature_data', sa.TEXT(), nullable=False),
    sa.Column('signed_value', sa.FLOAT(), nullable=False),
    sa.Column('signed_at', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('device_info', sa.VARCHAR(length=255), nullable=True),
    sa.Column('verification_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['monthly_account_id'], ['monthly_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_id'), 'signatures', ['id'], unique=False)
    op.create_table('monthly_account_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('monthly_account_id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('order_total', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['monthly_account_id'], ['monthly_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_account_items_id'), 'monthly_account_items', ['id'], unique=False)
    op.create_table('seasonality_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('period', sa.VARCHAR(length=20), nullable=False),
    sa.Column('period_value', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasonality_metrics_metric_type'), 'seasonality_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_seasonality_metrics_id'), 'seasonality_metrics', ['id'], unique=False)
    op.create_table('kitchen_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('order_item_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('preparation_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_orders_order_id'), 'kitchen_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_kitchen_orders_id'), 'kitchen_orders', ['id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('promotion_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('discount_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('discount_value', sa.FLOAT(), nullable=False),
    sa.Column('starts_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.TIME(), nullable=True),
    sa.Column('end_time', sa.TIME(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('purchase_date', sa.DATETIME(), nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=30), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_table('cash_registers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('opening_balance', sa.FLOAT(), nullable=True),
    sa.Column('expected_closing', sa.FLOAT(), nullable=True),
    sa.Column('informed_closing', sa.FLOAT(), nullable=True),
    sa.Column('difference', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('opened_by', sa.INTEGER(), nullable=False),
    sa.Column('closed_by', sa.INTEGER(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_registers_id'), 'cash_registers', ['id'], unique=False)
    op.create_index(op.f('ix_cash_registers_date'), 'cash_registers', ['date'], unique=1)
    op.create_table('role_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('discount_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('discount_value', sa.FLOAT(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), nullable=True),
    sa.Column('promotion_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_logs_order_id'), 'discount_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_discount_logs_id'), 'discount_logs', ['id'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=True),
    sa.Column('unit_measure', sa.VARCHAR(length=20), nullable=False),
    sa.Column('current_quantity', sa.FLOAT(), nullable=True),
    sa.Column('minimum_stock', sa.FLOAT(), nullable=True),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('average_cost', sa.FLOAT(), nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_name'), 'stock_items', ['name'], unique=False)
    op.create_index(op.f('ix_stock_items_id'), 'stock_items', ['id'], unique=False)
    op.create_table('loss_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stock_item_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit_measure', sa.VARCHAR(length=20), nullable=False),
    sa.Column('estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('loss_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loss_records_stock_item_id'), 'loss_records', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_loss_records_id'), 'loss_records', ['id'], unique=False)
    op.create_table('internal_consumptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('consumption_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('employee_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('authorized_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['authorized_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_consumptions_id'), 'internal_consumptions', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('expense_date', sa.DATE(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('estimated_cost', sa.FLOAT(), nullable=True),
    sa.Column('estimated_margin', sa.FLOAT(), nullable=True),
    sa.Column('avg_prep_time_minutes', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_seasonal', sa.BOOLEAN(), nullable=True),
    sa.Column('availability', sa.VARCHAR(length=30), nullable=True),
    sa.Column('seasonality', sqlite.JSON(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stock_item_id', sa.INTEGER(), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit_cost', sa.FLOAT(), nullable=True),
    sa.Column('total_cost', sa.FLOAT(), nullable=True),
    sa.Column('reference_id', sa.INTEGER(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_stock_item_id'), 'stock_movements', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('module', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_key'), 'permissions', ['key'], unique=1)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('document', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('company_sector', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('monthly_limit', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_item_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit_cost', sa.FLOAT(), nullable=False),
    sa.Column('total_cost', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('discount_value', sa.FLOAT(), nullable=False),
    sa.Column('max_uses', sa.INTEGER(), nullable=True),
    sa.Column('current_uses', sa.INTEGER(), nullable=True),
    sa.Column('starts_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=1)
    op.create_table('suppliers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category', sa.VARCHAR(length=80), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('biometric_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.Column('match_score', sa.INTEGER(), nullable=True),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('device_info', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['biometric_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_events_profile_id'), 'biometric_events', ['profile_id'], unique=False)
    op.create_index(op.f('ix_biometric_events_id'), 'biometric_events', ['id'], unique=False)
    op.create_index(op.f('ix_biometric_events_created_at'), 'biometric_events', ['created_at'], unique=False)
    op.create_table('biometric_consents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=50), nullable=False),
    sa.Column('consent_version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('device_info', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('granted_at', sa.DATETIME(), nullable=True),
    sa.Column('revoked_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['biometric_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometric_consents_id'), 'biometric_consents', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('tabs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tabs_id'), 'tabs', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=80), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('before_state', sqlite.JSON(), nullable=True),
    sa.Column('after_state', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
